In [445]:
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
from selenium import webdriver
# from selenium.webdriver.chrome.service import Service as ChromeService
# from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
import datetime
# from selenium.webdriver.support.ui import WebDriverWait
# from selenium.webdriver.support import expected_conditions


options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-gpu")
driver = webdriver.Chrome(options=options)

In [446]:
driver.get("https://www.nea.gov.sg/dengue-zika/dengue/dengue-clusters")
driver.maximize_window()
driver.implicitly_wait(2)
placesRAW = driver.find_elements(By.XPATH, '//tr[@data-row]')
casesSince2weeks = driver.find_elements(By.XPATH, '//td[4]')
casesSinceStart = driver.find_elements(By.XPATH, '//td[5]')

In [447]:
places = []
for place in placesRAW:
    places.append(place.get_attribute("id"))
print(places)

['AmoyStClubStClubStEmeraldGdnGemmillLnMccallumStTheCliftSouthBridgeRd', 'CountrysideRdLentorAveCresLkStTerLentorLoopBullionPk', 'CardiffGrCardiffResidenceGoldenDrRiseWalkJlnPacheliLiHwanClDrViewTaiHwanAveCresDrTer', 'CrossStMosqueStUppCrossStUppCrossStBlk532533535536538', 'TampinesSt22TampinesSt22Blk289294295296297298299A299B', 'JlnTenteramBlk161920116B117B', 'BuckleyRdBuckleyClassiqueChanceryLnChanceryLnChanceryEsquireDunearnRdChanceryCtEvelynRdGentleRdGilsteadRd', 'LeedonHtsLeedonHtsLeedonResidence', 'BtBatokCtrlBlk103106BtBatokWestAve6Blk111112', 'Lor1ToaPayohBlk113114115ToaPayohNorthBlk206209', 'ClementiWestSt2Blk706WestCoastRdBlk520701702703704', 'JlnGirangSgoonAve3Blk329331SgoonAve3TheSunnydale', 'NewMarketRdNewMarketRdBlk32PkRdPeoplesPkComplexUppCrossStUppCrossStBlk34', 'MeiHwanCresDr', 'BishanSt22Blk239242', 'BtBatokWestAve8Blk178183', 'Lor2ToaPayohBlk147', 'PandanGdnsBlk406412413', 'SgoonGdnWay', 'BtBatokEastAve3Blk285286287BtBatokEastAve4Blk274', 'CanberraCresBlk130ACanberraStBlk126A129A129B', 'JurongWestCtrl1Blk680A680BJurongWestSt64Blk676B', 'WoodlandsIndPkE5', 'AngMoKioAve10Blk410473476', 'AngMoKioAve4Blk106107', 'AngMoKioAve6Blk713716725', 'BendemeerRdBlk38B43', 'BishanSt22Blk232BishanSt24Blk286', 'BtBatokWestAve2BtBatokWestAve2Blk420422', 'DoverRdBlk123', 'FajarRdBlk418SaujanaRdBlk409415', 'FernvaleLnBlk405A405CFernvaleRdBlk406B', 'FuduPkLentorTer', 'JlnBtMerahBlk106108', 'JlnJambuBatuJlnJambuMawar', 'JlnKukohBlk23YorkHillBlk13', 'JurongWestCtrl1Blk692695JurongWestCtrl3Blk698A', 'JurongWestSt74Blk766JurongWestSt75', 'JurongWestSt93Blk965', 'KakiBtRd3', 'KretaAyerRdBlk333SagoLnBlk4SmithSt', 'Lor1ToaPayohBlk117118Lor2ToaPayohBlk116', 'Lor1ToaPayohBlk130A131B', 'MarineDrBlk6773', 'PunggolDrBlk619B', 'WestCoastCresWestCoastCresBlueHorizonTheVision', 'WoodlandsAve1Blk336337', 'AngMoKioAve1Blk216220', 'AngMoKioAve3Blk211212', 'AngMoKioAve3Blk313326', 'AngMoKioAve5Blk152180', 'BalamRdBlk33CircuitRdBlk37', 'BedokNorthDrBedokResidencesBedokNorthSt1Blk202', 'BedokReservoirRdBlk113120', 'BtMerahViewBlk130', 'CashewRdBlk135CashewRdCashewHts', 'ChempakaKuningLk', 'CommonwealthAveCommonwealthTwrs', 'CommonwealthCresBlk98101', 'DepotRdBlk104B106B', 'DevonshireRdOneDevonshireKillineyRdClaremont', 'GeylangEastAve1TreResidences', 'HougangAve2Blk706710', 'InternationalRd', 'JlnMatJambolBijou', 'JurongEastSt31Blk320323', 'JurongWestSt52Blk514515', 'KimChengStBlk45MohGuanTerBlk47', 'LavenderSt', 'MargaretDrBlk3739A', 'OceanDrTheOceanfrontSentosaCove', 'OldChoaChuKangRd', 'RivervaleDrBlk194', 'SegarRdBlossomResidences', 'SennettLnRd', 'SgoonNorthAve4Blk500534', 'SgoonRdRegentResidencesStGeorgeRdBlk10', 'SturdeeRdKerrisdale', 'TohGuanRdEast', 'WoodlandsDr73Blk685B', 'WoodlandsSt13Blk177183A']

In [448]:
showButtons = []
for place in places:
    showButtons.append(driver.find_element(By.XPATH, f'//*[@id="{place}"]/td[3]/p[1]'))
def closePopUp():
    driver.find_element(By.XPATH, '//*[@id="ClusterModal"]/div/div[1]/h2/span').click()
localities = []


for button in showButtons:
    button.click()
    driver.implicitly_wait(2)
    elements = driver.find_elements(By.XPATH, '//*[@id="modalBody"]/table/tbody')
    for element in elements:
        localities.append(element.text)
    driver.implicitly_wait(2)
    closePopUp()
localityFile = open("NeaLocalityData", "a")
localityFile.writelines(localities)
localityFile.close()

In [449]:
def fileFindnReplace(FileName, Find, Replace):
    file = open(FileName, "r")
    newContent = (file.read()).replace(Find, Replace)
    file.close()
    print(newContent[0])
    Data = open(FileName, "w")
    Data.write(newContent)
    Data.close()



fileFindnReplace("NeaLocalityData", "Location No. of Cases", "")
fileFindnReplace("NeaLocalityData", "\n(", " (")
file = open("NeaLocalityData", "r")
content = file.readlines()
for n, con in enumerate(content):
    if con == "\n":
        content.pop(n)
file.close()
file = open("NeaLocalityData", "w")
print(content)
if "\n" not in content[-1]:
    content[-1] = content[-1] + "\n"
file.writelines(content)
file.close()

['Amoy Street 1\n', 'Club Street 91\n', 'Club Street (Emerald Garden) 14\n', 'Gemmill Lane 1\n', 'Mccallum Street (The Clift) 1\n', 'South Bridge Road 1\n', 'Countryside Road 6\n', 'Lentor Avenue 1\n', 'Lentor Crescent 7\n', 'Lentor Link 4\n', 'Lentor Street 10\n', 'Lentor Terrace 1\n', 'Lentor Loop (Bullion Park) 52\n', 'Cardiff Grove (Cardiff Residence) 1\n', 'Golden Drive 12\n', 'Golden Rise 4\n', 'Golden Walk 7\n', 'Jalan Pacheli 5\n', 'Li Hwan Close 2\n', 'Li Hwan Drive 2\n', 'Li Hwan View 4\n', 'Tai Hwan Avenue 1\n', 'Tai Hwan Crescent 5\n', 'Tai Hwan Drive 1\n', 'Tai Hwan Terrace 1\n', 'Cross Street 17\n', 'Mosque Street 1\n', 'Upper Cross Street 1\n', 'Upper Cross Street (Blk 532) 3\n', 'Upper Cross Street (Blk 533) 4\n', 'Upper Cross Street (Blk 535) 4\n', 'Upper Cross Street (Blk 536) 2\n', 'Upper Cross Street (Blk 538) 3\n', 'Tampines Street 22 1\n', 'Tampines Street 22 (Blk 289) 1\n', 'Tampines Street 22 (Blk 294) 2\n', 'Tampines Street 22 (Blk 295) 6\n', 'Tampines Street 22 (Blk 296) 5\n', 'Tampines Street 22 (Blk 297) 14\n', 'Tampines Street 22 (Blk 298) 1\n', 'Tampines Street 22 (Blk 299A) 1\n', 'Tampines Street 22 (Blk 299B) 1\n', 'Jalan Tenteram (Blk 16) 3\n', 'Jalan Tenteram (Blk 19) 2\n', 'Jalan Tenteram (Blk 20) 10\n', 'Jalan Tenteram (Blk 116B) 2\n', 'Jalan Tenteram (Blk 117B) 1\n', 'Buckley Road (Buckley Classique) 1\n', 'Chancery Lane 1\n', 'Chancery Lane (Chancery Esquire) 1\n', 'Dunearn Road (Chancery Court) 1\n', 'Evelyn Road 1\n', 'Gentle Road 4\n', 'Gilstead Road 8\n', 'Leedon Heights 13\n', 'Leedon Heights (Leedon Residence) 2\n', 'Bukit Batok Central (Blk 103) 1\n', 'Bukit Batok Central (Blk 106) 5\n', 'Bukit Batok West Avenue 6 (Blk 111) 2\n', 'Bukit Batok West Avenue 6 (Blk 112) 2\n', 'Lorong 1 Toa Payoh (Blk 113) 1\n', 'Lorong 1 Toa Payoh (Blk 114) 1\n', 'Lorong 1 Toa Payoh (Blk 115) 4\n', 'Toa Payoh North (Blk 206) 2\n', 'Toa Payoh North (Blk 209) 2\n', 'Clementi West Street 2 (Blk 706) 1\n', 'West Coast Road (Blk 502) 1\n', 'West Coast Road (Blk 701) 1\n', 'West Coast Road (Blk 702) 2\n', 'West Coast Road (Blk 703) 1\n', 'West Coast Road (Blk 704) 1\n', 'Jalan Girang 1\n', 'Serangoon Avenue 3 (Blk 329) 4\n', 'Serangoon Avenue 3 (Blk 331) 1\n', 'Serangoon Avenue 3 (The Sunnydale) 1\n', 'New Market Road 1\n', 'New Market Road (Blk 32) 1\n', "Park Road (People's Park Complex) 1\n", 'Upper Cross Street 3\n', 'Upper Cross Street (Blk 34) 1\n', 'Mei Hwan Crescent 3\n', 'Mei Hwan Drive 3\n', 'Bishan Street 22 (Blk 239) 4\n', 'Bishan Street 22 (Blk 242) 1\n', 'Bukit Batok West Avenue 8 (Blk 178) 2\n', 'Bukit Batok West Avenue 8 (Blk 183) 3\n', 'Lorong 2 Toa Payoh (Blk 147) 5\n', 'Pandan Gardens (Blk 406) 1\n', 'Pandan Gardens (Blk 412) 2\n', 'Pandan Gardens (Blk 413) 2\n', 'Serangoon Garden Way 5\n', 'Bukit Batok East Avenue 3 (Blk 286) 1\n', 'Bukit Batok East Avenue 3 (Blk 285) 1\n', 'Bukit Batok East Avenue 3 (Blk 287) 1\n', 'Bukit Batok East Avenue 4 (Blk 274) 1\n', 'Canberra Crescent (Blk 130A) 1\n', 'Canberra Street (Blk 126A) 1\n', 'Canberra Street (Blk 129A) 1\n', 'Canberra Street (Blk 129B) 1\n', 'Jurong West Central 1 (Blk 680A) 1\n', 'Jurong West Central 1 (Blk 680B) 1\n', 'Jurong West Street 64 (Blk 676B) 2\n', 'Woodlands Industrial Park E5 4\n', 'Ang Mo Kio Avenue 10 (Blk 410) 1\n', 'Ang Mo Kio Avenue 10 (Blk 473) 1\n', 'Ang Mo Kio Avenue 10 (Blk 476) 1\n', 'Ang Mo Kio Avenue 4 (Blk 106) 1\n', 'Ang Mo Kio Avenue 4 (Blk 107) 2\n', 'Ang Mo Kio Avenue 6 (Blk 713) 1\n', 'Ang Mo Kio Avenue 6 (Blk 716) 1\n', 'Ang Mo Kio Avenue 6 (Blk 725) 1\n', 'Bendemeer Road (Blk 38B) 2\n', 'Bendemeer Road (Blk 43) 1\n', 'Bishan Street 22 (Blk 232) 1\n', 'Bishan Street 24 (Blk 286) 2\n', 'Bukit Batok West Avenue 2 1\n', 'Bukit Batok West Avenue 2 (Blk 420) 1\n', 'Bukit Batok West Avenue 2 (Blk 422) 1\n', 'Dover Road (Blk 1) 1\n', 'Dover Road (Blk 2) 1\n', 'Dover Road (Blk 3) 1\n', 'Fajar Road (Blk 418) 1\n', 'Saujana Road (Blk 409) 1\n', 'Saujana Road (Blk 415) 1\n', 'Fernvale Lane (Blk 405A) 1\n', 'Fernvale Lane (Blk 405C) 1\n', 'Fernvale Road (Blk 406B) 1\n', 'Fudu Park 1\n', 'Lentor Terrace 2\n', 'Jalan Bukit Merah (Blk 106) 2\n', 'Jalan Bukit Merah (Blk 108) 1\n', 'Jalan Jambu Batu 2\n', 'Jalan Jambu Mawar 1\n', 'Jalan Kukoh (Blk 2) 1\n', 'Jalan Kukoh (Blk 3) 1\n', 'York Hill (Blk 13) 1\n', 'Jurong West Central 1 (Blk 692) 1\n', 'Jurong West Central 1 (Blk 695) 1\n', 'Jurong West Central 3 (Blk 698A) 1\n', 'Jurong West Street 74 (Blk 766) 1\n', 'Jurong West Street 75 2\n', 'Jurong West Street 93 (Blk 965) 3\n', 'Kaki Bukit Road 3 3\n', 'Kreta Ayer Road (Blk 333) 1\n', 'Sago Lane (Blk 4) 1\n', 'Smith Street 1\n', 'Lorong 1 Toa Payoh (Blk 117) 1\n', 'Lorong 1 Toa Payoh (Blk 118) 1\n', 'Lorong 2 Toa Payoh (Blk 116) 1\n', 'Lorong 1 Toa Payoh (Blk 130A) 1\n', 'Lorong 1 Toa Payoh (Blk 131B) 2\n', 'Marine Drive (Blk 67) 2\n', 'Marine Drive (Blk 73) 1\n', 'Punggol Drive (Blk 619B) 3\n', 'West Coast Crescent 1\n', 'West Coast Crescent (Blue Horizon) 1\n', 'West Coast Crescent (The Vision) 1\n', 'Woodlands Avenue 1 (Blk 336) 2\n', 'Woodlands Avenue 1 (Blk 337) 1\n', 'Ang Mo Kio Avenue 1 (Blk 216) 1\n', 'Ang Mo Kio Avenue 1 (Blk 220) 1\n', 'Ang Mo Kio Avenue 3 (Blk 211) 1\n', 'Ang Mo Kio Avenue 3 (Blk 212) 1\n', 'Ang Mo Kio Avenue 3 (Blk 313) 1\n', 'Ang Mo Kio Avenue 3 (Blk 326) 1\n', 'Ang Mo Kio Avenue 5 (Blk 152) 1\n', 'Ang Mo Kio Avenue 5 (Blk 180) 1\n', 'Balam Road (Blk 33) 1\n', 'Circuit Road (Blk 37) 1\n', 'Bedok North Drive (Bedok Residences) 1\n', 'Bedok North Street 1 (Blk 202) 1\n', 'Bedok Reservoir Road (Blk 113) 1\n', 'Bedok Reservoir Road (Blk 120) 1\n', 'Bukit Merah View (Blk 130) 2\n', 'Cashew Road (Blk 135) 1\n', 'Cashew Road (Cashew Heights) 1\n', 'Chempaka Kuning Link 2\n', 'Commonwealth Avenue (Commonwealth Towers) 2\n', 'Commonwealth Crescent (Blk 98) 1\n', 'Commonwealth Crescent (Blk 101) 1\n', 'Depot Road (Blk 104B) 1\n', 'Depot Road (Blk 106B) 1\n', 'Devonshire Road (One Devonshire) 1\n', 'Killiney Road (Claremont) 1\n', 'Geylang East Avenue 1 (Tre Residences) 2\n', 'Hougang Avenue 2 (Blk 706) 1\n', 'Hougang Avenue 2 (Blk 710) 1\n', 'International Road 2\n', 'Jalan Mat Jambol (Bijou) 2\n', 'Jurong East Street 31 (Blk 320) 1\n', 'Jurong East Street 31 (Blk 323) 1\n', 'Jurong West Street 52 (Blk 514) 1\n', 'Jurong West Street 52 (Blk 515) 1\n', 'Kim Cheng Street (Blk 45) 1\n', 'Moh Guan Terrrace (Blk 47) 1\n', 'Lavender Street 2\n', 'Margaret Drive (Blk 37) 1\n', 'Margaret Drive (Blk 39A) 1\n', 'Ocean Drive (The Oceanfront @ Sentosa Cove) 2\n', 'Old Choa Chu Kang Road 2\n', 'Rivervale Drive (Blk 194) 2\n', 'Segar Road (Blossom Residences) 2\n', 'Sennett Lane 1\n', 'Sennett Road 1\n', 'Serangoon North Avenue 4 (Blk 500) 1\n', 'Serangoon North Avenue 4 (Blk 534) 1\n', 'Serangoon Road (Regent Residences) 1\n', 'Saint George Road (Blk 10) 1\n', 'Sturdee Road (Kerrisdale) 2\n', 'Toh Guan Road East 2\n', 'Woodlands Drive 73 (Blk 685B) 2\n', 'Woodlands Street 13 (Blk 177) 1\n', 'Woodlands Street 13 (Blk 183A) 1']

In [450]:
file = open("NeaLocalityData", "r")
lines = file.readlines()
newLines = []
for line in lines:
    newLine = line
    try:
        if line[-4].isdigit() and line[-3].isdigit() and line[-2].isdigit():
            newLine = line[:-5] + "," + line[-4:]
        
        elif line[-3].isdigit() and line[-2].isdigit():
            newLine = line[:-4] + "," +  line[-3:]

        elif line[-2].isdigit():
            newLine = line[:-3] + "," +  line[-2:]
    except IndexError:
        pass
    newLines.append(newLine)
file = open("NeaLocalityData", "w")
file.writelines(newLines)
file.close()

In [451]:
cases2weeks = []
for num in casesSince2weeks:
    cases2weeks.append(num.text) 
print(cases2weeks) 
CasesStart = []

['13', '7', '4', '7', '3', '7', '2', '2', '4', '7', '4', '4', '5', '1', '3', '1', '3', '1', '2', '1', '3', '4', '3', '3', '1', '3', '3', '3', '2', '2', '3', '1', '3', '1', '1', '2', '2', '2', '3', '2', '1', '3', '1', '1', '3', '1', '2', '1', '2', '1', '2', '2', '2', '1', '1', '1', '1', '2', '1', '1', '1', '1', '2', '1', '2', '2', '1', '1', '1', '1', '1', '1', '1', '1', '2', '1', '2', '1', '1', '2', '2']

In [452]:
for num in casesSinceStart:
    CasesStart.append(num.text)
print(CasesStart)
driver.close()

['109', '81', '45', '35', '32', '18', '17', '15', '10', '10', '7', '7', '7', '6', '5', '5', '5', '5', '5', '4', '4', '4', '4', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2']

In [453]:
newPlaces = []
for place in places:
    newplace = ""
    for i, char in enumerate(place):
        if char.isupper():
            newplace += " " + char
        else:
            newplace += char
    newPlaces.append(newplace)
print(newPlaces)

[' Amoy St Club St Club St Emerald Gdn Gemmill Ln Mccallum St The Clift South Bridge Rd', ' Countryside Rd Lentor Ave Cres Lk St Ter Lentor Loop Bullion Pk', ' Cardiff Gr Cardiff Residence Golden Dr Rise Walk Jln Pacheli Li Hwan Cl Dr View Tai Hwan Ave Cres Dr Ter', ' Cross St Mosque St Upp Cross St Upp Cross St Blk532533535536538', ' Tampines St22 Tampines St22 Blk289294295296297298299 A299 B', ' Jln Tenteram Blk161920116 B117 B', ' Buckley Rd Buckley Classique Chancery Ln Chancery Ln Chancery Esquire Dunearn Rd Chancery Ct Evelyn Rd Gentle Rd Gilstead Rd', ' Leedon Hts Leedon Hts Leedon Residence', ' Bt Batok Ctrl Blk103106 Bt Batok West Ave6 Blk111112', ' Lor1 Toa Payoh Blk113114115 Toa Payoh North Blk206209', ' Clementi West St2 Blk706 West Coast Rd Blk520701702703704', ' Jln Girang Sgoon Ave3 Blk329331 Sgoon Ave3 The Sunnydale', ' New Market Rd New Market Rd Blk32 Pk Rd Peoples Pk Complex Upp Cross St Upp Cross St Blk34', ' Mei Hwan Cres Dr', ' Bishan St22 Blk239242', ' Bt Batok West Ave8 Blk178183', ' Lor2 Toa Payoh Blk147', ' Pandan Gdns Blk406412413', ' Sgoon Gdn Way', ' Bt Batok East Ave3 Blk285286287 Bt Batok East Ave4 Blk274', ' Canberra Cres Blk130 A Canberra St Blk126 A129 A129 B', ' Jurong West Ctrl1 Blk680 A680 B Jurong West St64 Blk676 B', ' Woodlands Ind Pk E5', ' Ang Mo Kio Ave10 Blk410473476', ' Ang Mo Kio Ave4 Blk106107', ' Ang Mo Kio Ave6 Blk713716725', ' Bendemeer Rd Blk38 B43', ' Bishan St22 Blk232 Bishan St24 Blk286', ' Bt Batok West Ave2 Bt Batok West Ave2 Blk420422', ' Dover Rd Blk123', ' Fajar Rd Blk418 Saujana Rd Blk409415', ' Fernvale Ln Blk405 A405 C Fernvale Rd Blk406 B', ' Fudu Pk Lentor Ter', ' Jln Bt Merah Blk106108', ' Jln Jambu Batu Jln Jambu Mawar', ' Jln Kukoh Blk23 York Hill Blk13', ' Jurong West Ctrl1 Blk692695 Jurong West Ctrl3 Blk698 A', ' Jurong West St74 Blk766 Jurong West St75', ' Jurong West St93 Blk965', ' Kaki Bt Rd3', ' Kreta Ayer Rd Blk333 Sago Ln Blk4 Smith St', ' Lor1 Toa Payoh Blk117118 Lor2 Toa Payoh Blk116', ' Lor1 Toa Payoh Blk130 A131 B', ' Marine Dr Blk6773', ' Punggol Dr Blk619 B', ' West Coast Cres West Coast Cres Blue Horizon The Vision', ' Woodlands Ave1 Blk336337', ' Ang Mo Kio Ave1 Blk216220', ' Ang Mo Kio Ave3 Blk211212', ' Ang Mo Kio Ave3 Blk313326', ' Ang Mo Kio Ave5 Blk152180', ' Balam Rd Blk33 Circuit Rd Blk37', ' Bedok North Dr Bedok Residences Bedok North St1 Blk202', ' Bedok Reservoir Rd Blk113120', ' Bt Merah View Blk130', ' Cashew Rd Blk135 Cashew Rd Cashew Hts', ' Chempaka Kuning Lk', ' Commonwealth Ave Commonwealth Twrs', ' Commonwealth Cres Blk98101', ' Depot Rd Blk104 B106 B', ' Devonshire Rd One Devonshire Killiney Rd Claremont', ' Geylang East Ave1 Tre Residences', ' Hougang Ave2 Blk706710', ' International Rd', ' Jln Mat Jambol Bijou', ' Jurong East St31 Blk320323', ' Jurong West St52 Blk514515', ' Kim Cheng St Blk45 Moh Guan Ter Blk47', ' Lavender St', ' Margaret Dr Blk3739 A', ' Ocean Dr The Oceanfront Sentosa Cove', ' Old Choa Chu Kang Rd', ' Rivervale Dr Blk194', ' Segar Rd Blossom Residences', ' Sennett Ln Rd', ' Sgoon North Ave4 Blk500534', ' Sgoon Rd Regent Residences St George Rd Blk10', ' Sturdee Rd Kerrisdale', ' Toh Guan Rd East', ' Woodlands Dr73 Blk685 B', ' Woodlands St13 Blk177183 A']

In [454]:
data = pd.DataFrame(list(zip(newPlaces, cases2weeks, CasesStart)), columns=["cluster address", "cases in last 2 weeks", "cases since beginning of cluster"])
count = data.count()
numOfRows = count.iloc[0]
dateExtractedCol = []
extractionDate = datetime.date.today()
for _ in range(numOfRows):
    dateExtractedCol.append(extractionDate)
dateExtractedCol

[datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12)]

In [455]:
data["date of extraction"] = dateExtractedCol
data

,cluster address,cases in last 2 weeks,cases since beginning of cluster,date of extraction
0,Amoy St Club St Club St Emerald Gdn Gemmill L...,13,109,2023-10-12
1,Countryside Rd Lentor Ave Cres Lk St Ter Lent...,7,81,2023-10-12
2,Cardiff Gr Cardiff Residence Golden Dr Rise W...,4,45,2023-10-12
3,Cross St Mosque St Upp Cross St Upp Cross St ...,7,35,2023-10-12
4,Tampines St22 Tampines St22 Blk28929429529629...,3,32,2023-10-12
...,...,...,...,...
76,Sgoon Rd Regent Residences St George Rd Blk10,2,2,2023-10-12
77,Sturdee Rd Kerrisdale,1,2,2023-10-12
78,Toh Guan Rd East,1,2,2023-10-12
79,Woodlands Dr73 Blk685 B,2,2,2023-10-12
80,Woodlands St13 Blk177183 A,2,2,2023-10-12

In [456]:

file = open("NeaDataOverview", "a")
csv = data.to_csv(index=False, header=False)
file.writelines(csv)
file.close()

In [457]:
testdata = pd.read_csv("NeaDataOverview")
testdata

,place,cases last two weeks,total cases,extraction date
0,Amoy St Club St Club St Emerald Gdn Gemmill L...,13,109,2023-10-12
1,Countryside Rd Lentor Ave Cres Lk St Ter Lent...,7,81,2023-10-12
2,Cardiff Gr Cardiff Residence Golden Dr Rise W...,4,45,2023-10-12
3,Cross St Mosque St Upp Cross St Upp Cross St ...,7,35,2023-10-12
4,Tampines St22 Tampines St22 Blk28929429529629...,3,32,2023-10-12
...,...,...,...,...
76,Sgoon Rd Regent Residences St George Rd Blk10,2,2,2023-10-12
77,Sturdee Rd Kerrisdale,1,2,2023-10-12
78,Toh Guan Rd East,1,2,2023-10-12
79,Woodlands Dr73 Blk685 B,2,2,2023-10-12
80,Woodlands St13 Blk177183 A,2,2,2023-10-12

In [458]:
localityData = pd.read_csv("NeaLocalityData")
localityData

                        Amoy Street   1
0                       Club Street  91
1      Club Street (Emerald Garden)  14
2                      Gemmill Lane   1
3       Mccallum Street (The Clift)   1
4                 South Bridge Road   1
..                              ...  ..
207       Sturdee Road (Kerrisdale)   2
208              Toh Guan Road East   2
209   Woodlands Drive 73 (Blk 685B)   2
210   Woodlands Street 13 (Blk 177)   1
211  Woodlands Street 13 (Blk 183A)   1

[212 rows x 2 columns]

In [459]:
count = localityData.count()
numOfRows = count.iloc[0]
dateExtractedColLocal = []
extractionDate = datetime.date.today()
for _ in range(numOfRows):
    dateExtractedColLocal.append(extractionDate)
dateExtractedColLocal

[datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12),
 datetime.date(2023, 10, 12)]

In [460]:
localityData["date of extraction"] = dateExtractedColLocal

In [461]:
file = open("NeaDataLocalities", "a")
csv = localityData.to_csv(index=False, header=False)
file.writelines(csv)
file.close()

In [462]:
file = open("NeaLocalityData", "w")
file.write("")

file.close()
file = open("NeaDataLocalities", "r")
content = file.readlines()
for n, con in enumerate(content):
    if con == "\n":
        content.pop(n)
file.close()
file = open("NeaDataLocalities", "w")
print(content)
if "\n" not in content[-1]:
    content[-1] = content[-1] + "\n"
file.writelines(content)
file.close()
file = open("NeaDataOverview", "r")
content = file.readlines()
for n, con in enumerate(content):
    if con == "\n":
        content.pop(n)
file.close()
file = open("NeaDataOverview", "w")
print(content)
if "\n" not in content[-1]:
    content[-1] = content[-1] + "\n"
file.writelines(content)
file.close()

['place, no of case, extraction date\n', 'Club Street,91,2023-10-12\n', 'Club Street (Emerald Garden),14,2023-10-12\n', 'Gemmill Lane,1,2023-10-12\n', 'Mccallum Street (The Clift),1,2023-10-12\n', 'South Bridge Road,1,2023-10-12\n', 'Countryside Road,6,2023-10-12\n', 'Lentor Avenue,1,2023-10-12\n', 'Lentor Crescent,7,2023-10-12\n', 'Lentor Link,4,2023-10-12\n', 'Lentor Street,10,2023-10-12\n', 'Lentor Terrace,1,2023-10-12\n', 'Lentor Loop (Bullion Park),52,2023-10-12\n', 'Cardiff Grove (Cardiff Residence),1,2023-10-12\n', 'Golden Drive,12,2023-10-12\n', 'Golden Rise,4,2023-10-12\n', 'Golden Walk,7,2023-10-12\n', 'Jalan Pacheli,5,2023-10-12\n', 'Li Hwan Close,2,2023-10-12\n', 'Li Hwan Drive,2,2023-10-12\n', 'Li Hwan View,4,2023-10-12\n', 'Tai Hwan Avenue,1,2023-10-12\n', 'Tai Hwan Crescent,5,2023-10-12\n', 'Tai Hwan Drive,1,2023-10-12\n', 'Tai Hwan Terrace,1,2023-10-12\n', 'Cross Street,17,2023-10-12\n', 'Mosque Street,1,2023-10-12\n', 'Upper Cross Street,1,2023-10-12\n', 'Upper Cross Street (Blk 532),3,2023-10-12\n', 'Upper Cross Street (Blk 533),4,2023-10-12\n', 'Upper Cross Street (Blk 535),4,2023-10-12\n', 'Upper Cross Street (Blk 536),2,2023-10-12\n', 'Upper Cross Street (Blk 538),3,2023-10-12\n', 'Tampines Street 22,1,2023-10-12\n', 'Tampines Street 22 (Blk 289),1,2023-10-12\n', 'Tampines Street 22 (Blk 294),2,2023-10-12\n', 'Tampines Street 22 (Blk 295),6,2023-10-12\n', 'Tampines Street 22 (Blk 296),5,2023-10-12\n', 'Tampines Street 22 (Blk 297),14,2023-10-12\n', 'Tampines Street 22 (Blk 298),1,2023-10-12\n', 'Tampines Street 22 (Blk 299A),1,2023-10-12\n', 'Tampines Street 22 (Blk 299B),1,2023-10-12\n', 'Jalan Tenteram (Blk 16),3,2023-10-12\n', 'Jalan Tenteram (Blk 19),2,2023-10-12\n', 'Jalan Tenteram (Blk 20),10,2023-10-12\n', 'Jalan Tenteram (Blk 116B),2,2023-10-12\n', 'Jalan Tenteram (Blk 117B),1,2023-10-12\n', 'Buckley Road (Buckley Classique),1,2023-10-12\n', 'Chancery Lane,1,2023-10-12\n', 'Chancery Lane (Chancery Esquire),1,2023-10-12\n', 'Dunearn Road (Chancery Court),1,2023-10-12\n', 'Evelyn Road,1,2023-10-12\n', 'Gentle Road,4,2023-10-12\n', 'Gilstead Road,8,2023-10-12\n', 'Leedon Heights,13,2023-10-12\n', 'Leedon Heights (Leedon Residence),2,2023-10-12\n', 'Bukit Batok Central (Blk 103),1,2023-10-12\n', 'Bukit Batok Central (Blk 106),5,2023-10-12\n', 'Bukit Batok West Avenue 6 (Blk 111),2,2023-10-12\n', 'Bukit Batok West Avenue 6 (Blk 112),2,2023-10-12\n', 'Lorong 1 Toa Payoh (Blk 113),1,2023-10-12\n', 'Lorong 1 Toa Payoh (Blk 114),1,2023-10-12\n', 'Lorong 1 Toa Payoh (Blk 115),4,2023-10-12\n', 'Toa Payoh North (Blk 206),2,2023-10-12\n', 'Toa Payoh North (Blk 209),2,2023-10-12\n', 'Clementi West Street 2 (Blk 706),1,2023-10-12\n', 'West Coast Road (Blk 502),1,2023-10-12\n', 'West Coast Road (Blk 701),1,2023-10-12\n', 'West Coast Road (Blk 702),2,2023-10-12\n', 'West Coast Road (Blk 703),1,2023-10-12\n', 'West Coast Road (Blk 704),1,2023-10-12\n', 'Jalan Girang,1,2023-10-12\n', 'Serangoon Avenue 3 (Blk 329),4,2023-10-12\n', 'Serangoon Avenue 3 (Blk 331),1,2023-10-12\n', 'Serangoon Avenue 3 (The Sunnydale),1,2023-10-12\n', 'New Market Road,1,2023-10-12\n', 'New Market Road (Blk 32),1,2023-10-12\n', "Park Road (People's Park Complex),1,2023-10-12\n", 'Upper Cross Street,3,2023-10-12\n', 'Upper Cross Street (Blk 34),1,2023-10-12\n', 'Mei Hwan Crescent,3,2023-10-12\n', 'Mei Hwan Drive,3,2023-10-12\n', 'Bishan Street 22 (Blk 239),4,2023-10-12\n', 'Bishan Street 22 (Blk 242),1,2023-10-12\n', 'Bukit Batok West Avenue 8 (Blk 178),2,2023-10-12\n', 'Bukit Batok West Avenue 8 (Blk 183),3,2023-10-12\n', 'Lorong 2 Toa Payoh (Blk 147),5,2023-10-12\n', 'Pandan Gardens (Blk 406),1,2023-10-12\n', 'Pandan Gardens (Blk 412),2,2023-10-12\n', 'Pandan Gardens (Blk 413),2,2023-10-12\n', 'Serangoon Garden Way,5,2023-10-12\n', 'Bukit Batok East Avenue 3 (Blk 286),1,2023-10-12\n', 'Bukit Batok East Avenue 3 (Blk 285),1,2023-10-12\n', 'Bukit Batok East Avenue 3 (Blk 287),1,2023-10-12\n', 'Bukit Batok East Avenue 4 (Blk 274),1,2023-10-12\n', 'Canberra Crescent (Blk 130A),1,2023-10-12\n', 'Canberra Street (Blk 126A),1,2023-10-12\n', 'Canberra Street (Blk 129A),1,2023-10-12\n', 'Canberra Street (Blk 129B),1,2023-10-12\n', 'Jurong West Central 1 (Blk 680A),1,2023-10-12\n', 'Jurong West Central 1 (Blk 680B),1,2023-10-12\n', 'Jurong West Street 64 (Blk 676B),2,2023-10-12\n', 'Woodlands Industrial Park E5,4,2023-10-12\n', 'Ang Mo Kio Avenue 10 (Blk 410),1,2023-10-12\n', 'Ang Mo Kio Avenue 10 (Blk 473),1,2023-10-12\n', 'Ang Mo Kio Avenue 10 (Blk 476),1,2023-10-12\n', 'Ang Mo Kio Avenue 4 (Blk 106),1,2023-10-12\n', 'Ang Mo Kio Avenue 4 (Blk 107),2,2023-10-12\n', 'Ang Mo Kio Avenue 6 (Blk 713),1,2023-10-12\n', 'Ang Mo Kio Avenue 6 (Blk 716),1,2023-10-12\n', 'Ang Mo Kio Avenue 6 (Blk 725),1,2023-10-12\n', 'Bendemeer Road (Blk 38B),2,2023-10-12\n', 'Bendemeer Road (Blk 43),1,2023-10-12\n', 'Bishan Street 22 (Blk 232),1,2023-10-12\n', 'Bishan Street 24 (Blk 286),2,2023-10-12\n', 'Bukit Batok West Avenue 2,1,2023-10-12\n', 'Bukit Batok West Avenue 2 (Blk 420),1,2023-10-12\n', 'Bukit Batok West Avenue 2 (Blk 422),1,2023-10-12\n', 'Dover Road (Blk 1),1,2023-10-12\n', 'Dover Road (Blk 2),1,2023-10-12\n', 'Dover Road (Blk 3),1,2023-10-12\n', 'Fajar Road (Blk 418),1,2023-10-12\n', 'Saujana Road (Blk 409),1,2023-10-12\n', 'Saujana Road (Blk 415),1,2023-10-12\n', 'Fernvale Lane (Blk 405A),1,2023-10-12\n', 'Fernvale Lane (Blk 405C),1,2023-10-12\n', 'Fernvale Road (Blk 406B),1,2023-10-12\n', 'Fudu Park,1,2023-10-12\n', 'Lentor Terrace,2,2023-10-12\n', 'Jalan Bukit Merah (Blk 106),2,2023-10-12\n', 'Jalan Bukit Merah (Blk 108),1,2023-10-12\n', 'Jalan Jambu Batu,2,2023-10-12\n', 'Jalan Jambu Mawar,1,2023-10-12\n', 'Jalan Kukoh (Blk 2),1,2023-10-12\n', 'Jalan Kukoh (Blk 3),1,2023-10-12\n', 'York Hill (Blk 13),1,2023-10-12\n', 'Jurong West Central 1 (Blk 692),1,2023-10-12\n', 'Jurong West Central 1 (Blk 695),1,2023-10-12\n', 'Jurong West Central 3 (Blk 698A),1,2023-10-12\n', 'Jurong West Street 74 (Blk 766),1,2023-10-12\n', 'Jurong West Street 75,2,2023-10-12\n', 'Jurong West Street 93 (Blk 965),3,2023-10-12\n', 'Kaki Bukit Road 3,3,2023-10-12\n', 'Kreta Ayer Road (Blk 333),1,2023-10-12\n', 'Sago Lane (Blk 4),1,2023-10-12\n', 'Smith Street,1,2023-10-12\n', 'Lorong 1 Toa Payoh (Blk 117),1,2023-10-12\n', 'Lorong 1 Toa Payoh (Blk 118),1,2023-10-12\n', 'Lorong 2 Toa Payoh (Blk 116),1,2023-10-12\n', 'Lorong 1 Toa Payoh (Blk 130A),1,2023-10-12\n', 'Lorong 1 Toa Payoh (Blk 131B),2,2023-10-12\n', 'Marine Drive (Blk 67),2,2023-10-12\n', 'Marine Drive (Blk 73),1,2023-10-12\n', 'Punggol Drive (Blk 619B),3,2023-10-12\n', 'West Coast Crescent,1,2023-10-12\n', 'West Coast Crescent (Blue Horizon),1,2023-10-12\n', 'West Coast Crescent (The Vision),1,2023-10-12\n', 'Woodlands Avenue 1 (Blk 336),2,2023-10-12\n', 'Woodlands Avenue 1 (Blk 337),1,2023-10-12\n', 'Ang Mo Kio Avenue 1 (Blk 216),1,2023-10-12\n', 'Ang Mo Kio Avenue 1 (Blk 220),1,2023-10-12\n', 'Ang Mo Kio Avenue 3 (Blk 211),1,2023-10-12\n', 'Ang Mo Kio Avenue 3 (Blk 212),1,2023-10-12\n', 'Ang Mo Kio Avenue 3 (Blk 313),1,2023-10-12\n', 'Ang Mo Kio Avenue 3 (Blk 326),1,2023-10-12\n', 'Ang Mo Kio Avenue 5 (Blk 152),1,2023-10-12\n', 'Ang Mo Kio Avenue 5 (Blk 180),1,2023-10-12\n', 'Balam Road (Blk 33),1,2023-10-12\n', 'Circuit Road (Blk 37),1,2023-10-12\n', 'Bedok North Drive (Bedok Residences),1,2023-10-12\n', 'Bedok North Street 1 (Blk 202),1,2023-10-12\n', 'Bedok Reservoir Road (Blk 113),1,2023-10-12\n', 'Bedok Reservoir Road (Blk 120),1,2023-10-12\n', 'Bukit Merah View (Blk 130),2,2023-10-12\n', 'Cashew Road (Blk 135),1,2023-10-12\n', 'Cashew Road (Cashew Heights),1,2023-10-12\n', 'Chempaka Kuning Link,2,2023-10-12\n', 'Commonwealth Avenue (Commonwealth Towers),2,2023-10-12\n', 'Commonwealth Crescent (Blk 98),1,2023-10-12\n', 'Commonwealth Crescent (Blk 101),1,2023-10-12\n', 'Depot Road (Blk 104B),1,2023-10-12\n', 'Depot Road (Blk 106B),1,2023-10-12\n', 'Devonshire Road (One Devonshire),1,2023-10-12\n', 'Killiney Road (Claremont),1,2023-10-12\n', 'Geylang East Avenue 1 (Tre Residences),2,2023-10-12\n', 'Hougang Avenue 2 (Blk 706),1,2023-10-12\n', 'Hougang Avenue 2 (Blk 710),1,2023-10-12\n', 'International Road,2,2023-10-12\n', 'Jalan Mat Jambol (Bijou),2,2023-10-12\n', 'Jurong East Street 31 (Blk 320),1,2023-10-12\n', 'Jurong East Street 31 (Blk 323),1,2023-10-12\n', 'Jurong West Street 52 (Blk 514),1,2023-10-12\n', 'Jurong West Street 52 (Blk 515),1,2023-10-12\n', 'Kim Cheng Street (Blk 45),1,2023-10-12\n', 'Moh Guan Terrrace (Blk 47),1,2023-10-12\n', 'Lavender Street,2,2023-10-12\n', 'Margaret Drive (Blk 37),1,2023-10-12\n', 'Margaret Drive (Blk 39A),1,2023-10-12\n', 'Ocean Drive (The Oceanfront @ Sentosa Cove),2,2023-10-12\n', 'Old Choa Chu Kang Road,2,2023-10-12\n', 'Rivervale Drive (Blk 194),2,2023-10-12\n', 'Segar Road (Blossom Residences),2,2023-10-12\n', 'Sennett Lane,1,2023-10-12\n', 'Sennett Road,1,2023-10-12\n', 'Serangoon North Avenue 4 (Blk 500),1,2023-10-12\n', 'Serangoon North Avenue 4 (Blk 534),1,2023-10-12\n', 'Serangoon Road (Regent Residences),1,2023-10-12\n', 'Saint George Road (Blk 10),1,2023-10-12\n', 'Sturdee Road (Kerrisdale),2,2023-10-12\n', 'Toh Guan Road East,2,2023-10-12\n', 'Woodlands Drive 73 (Blk 685B),2,2023-10-12\n', 'Woodlands Street 13 (Blk 177),1,2023-10-12\n', 'Woodlands Street 13 (Blk 183A),1,2023-10-12\n']
['place, cases last two weeks, total cases, extraction date\n', ' Amoy St Club St Club St Emerald Gdn Gemmill Ln Mccallum St The Clift South Bridge Rd,13,109,2023-10-12\n', ' Countryside Rd Lentor Ave Cres Lk St Ter Lentor Loop Bullion Pk,7,81,2023-10-12\n', ' Cardiff Gr Cardiff Residence Golden Dr Rise Walk Jln Pacheli Li Hwan Cl Dr View Tai Hwan Ave Cres Dr Ter,4,45,2023-10-12\n', ' Cross St Mosque St Upp Cross St Upp Cross St Blk532533535536538,7,35,2023-10-12\n', ' Tampines St22 Tampines St22 Blk289294295296297298299 A299 B,3,32,2023-10-12\n', ' Jln Tenteram Blk161920116 B117 B,7,18,2023-10-12\n', ' Buckley Rd Buckley Classique Chancery Ln Chancery Ln Chancery Esquire Dunearn Rd Chancery Ct Evelyn Rd Gentle Rd Gilstead Rd,2,17,2023-10-12\n', ' Leedon Hts Leedon Hts Leedon Residence,2,15,2023-10-12\n', ' Bt Batok Ctrl Blk103106 Bt Batok West Ave6 Blk111112,4,10,2023-10-12\n', ' Lor1 Toa Payoh Blk113114115 Toa Payoh North Blk206209,7,10,2023-10-12\n', ' Clementi West St2 Blk706 West Coast Rd Blk520701702703704,4,7,2023-10-12\n', ' Jln Girang Sgoon Ave3 Blk329331 Sgoon Ave3 The Sunnydale,4,7,2023-10-12\n', ' New Market Rd New Market Rd Blk32 Pk Rd Peoples Pk Complex Upp Cross St Upp Cross St Blk34,5,7,2023-10-12\n', ' Mei Hwan Cres Dr,1,6,2023-10-12\n', ' Bishan St22 Blk239242,3,5,2023-10-12\n', ' Bt Batok West Ave8 Blk178183,1,5,2023-10-12\n', ' Lor2 Toa Payoh Blk147,3,5,2023-10-12\n', ' Pandan Gdns Blk406412413,1,5,2023-10-12\n', ' Sgoon Gdn Way,2,5,2023-10-12\n', ' Bt Batok East Ave3 Blk285286287 Bt Batok East Ave4 Blk274,1,4,2023-10-12\n', ' Canberra Cres Blk130 A Canberra St Blk126 A129 A129 B,3,4,2023-10-12\n', ' Jurong West Ctrl1 Blk680 A680 B Jurong West St64 Blk676 B,4,4,2023-10-12\n', ' Woodlands Ind Pk E5,3,4,2023-10-12\n', ' Ang Mo Kio Ave10 Blk410473476,3,3,2023-10-12\n', ' Ang Mo Kio Ave4 Blk106107,1,3,2023-10-12\n', ' Ang Mo Kio Ave6 Blk713716725,3,3,2023-10-12\n', ' Bendemeer Rd Blk38 B43,3,3,2023-10-12\n', ' Bishan St22 Blk232 Bishan St24 Blk286,3,3,2023-10-12\n', ' Bt Batok West Ave2 Bt Batok West Ave2 Blk420422,2,3,2023-10-12\n', ' Dover Rd Blk123,2,3,2023-10-12\n', ' Fajar Rd Blk418 Saujana Rd Blk409415,3,3,2023-10-12\n', ' Fernvale Ln Blk405 A405 C Fernvale Rd Blk406 B,1,3,2023-10-12\n', ' Fudu Pk Lentor Ter,3,3,2023-10-12\n', ' Jln Bt Merah Blk106108,1,3,2023-10-12\n', ' Jln Jambu Batu Jln Jambu Mawar,1,3,2023-10-12\n', ' Jln Kukoh Blk23 York Hill Blk13,2,3,2023-10-12\n', ' Jurong West Ctrl1 Blk692695 Jurong West Ctrl3 Blk698 A,2,3,2023-10-12\n', ' Jurong West St74 Blk766 Jurong West St75,2,3,2023-10-12\n', ' Jurong West St93 Blk965,3,3,2023-10-12\n', ' Kaki Bt Rd3,2,3,2023-10-12\n', ' Kreta Ayer Rd Blk333 Sago Ln Blk4 Smith St,1,3,2023-10-12\n', ' Lor1 Toa Payoh Blk117118 Lor2 Toa Payoh Blk116,3,3,2023-10-12\n', ' Lor1 Toa Payoh Blk130 A131 B,1,3,2023-10-12\n', ' Marine Dr Blk6773,1,3,2023-10-12\n', ' Punggol Dr Blk619 B,3,3,2023-10-12\n', ' West Coast Cres West Coast Cres Blue Horizon The Vision,1,3,2023-10-12\n', ' Woodlands Ave1 Blk336337,2,3,2023-10-12\n', ' Ang Mo Kio Ave1 Blk216220,1,2,2023-10-12\n', ' Ang Mo Kio Ave3 Blk211212,2,2,2023-10-12\n', ' Ang Mo Kio Ave3 Blk313326,1,2,2023-10-12\n', ' Ang Mo Kio Ave5 Blk152180,2,2,2023-10-12\n', ' Balam Rd Blk33 Circuit Rd Blk37,2,2,2023-10-12\n', ' Bedok North Dr Bedok Residences Bedok North St1 Blk202,2,2,2023-10-12\n', ' Bedok Reservoir Rd Blk113120,1,2,2023-10-12\n', ' Bt Merah View Blk130,1,2,2023-10-12\n', ' Cashew Rd Blk135 Cashew Rd Cashew Hts,1,2,2023-10-12\n', ' Chempaka Kuning Lk,1,2,2023-10-12\n', ' Commonwealth Ave Commonwealth Twrs,2,2,2023-10-12\n', ' Commonwealth Cres Blk98101,1,2,2023-10-12\n', ' Depot Rd Blk104 B106 B,1,2,2023-10-12\n', ' Devonshire Rd One Devonshire Killiney Rd Claremont,1,2,2023-10-12\n', ' Geylang East Ave1 Tre Residences,1,2,2023-10-12\n', ' Hougang Ave2 Blk706710,2,2,2023-10-12\n', ' International Rd,1,2,2023-10-12\n', ' Jln Mat Jambol Bijou,2,2,2023-10-12\n', ' Jurong East St31 Blk320323,2,2,2023-10-12\n', ' Jurong West St52 Blk514515,1,2,2023-10-12\n', ' Kim Cheng St Blk45 Moh Guan Ter Blk47,1,2,2023-10-12\n', ' Lavender St,1,2,2023-10-12\n', ' Margaret Dr Blk3739 A,1,2,2023-10-12\n', ' Ocean Dr The Oceanfront Sentosa Cove,1,2,2023-10-12\n', ' Old Choa Chu Kang Rd,1,2,2023-10-12\n', ' Rivervale Dr Blk194,1,2,2023-10-12\n', ' Segar Rd Blossom Residences,1,2,2023-10-12\n', ' Sennett Ln Rd,2,2,2023-10-12\n', ' Sgoon North Ave4 Blk500534,1,2,2023-10-12\n', ' Sgoon Rd Regent Residences St George Rd Blk10,2,2,2023-10-12\n', ' Sturdee Rd Kerrisdale,1,2,2023-10-12\n', ' Toh Guan Rd East,1,2,2023-10-12\n', ' Woodlands Dr73 Blk685 B,2,2,2023-10-12\n', ' Woodlands St13 Blk177183 A,2,2,2023-10-12\n']